### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mikhoul** [intact/livestreamer#3]
Hi @intact ,

I'm new to livestreamer and I see that your fork is active looking at the commit but I don't see any installer for Windows.

Do you have one folder/repo where the last version is compiled for Windows ?

Regards !  :octocat:

**Comment by intact** [comment]
Hi

> Do you have one folder/repo where the last version is compiled for Windows ?

No :)

Maybe you can try https://github.com/streamlink/streamlink (if you need Windows installer)

**Comment by mikhoul** [comment]
Thanks !  👍
